version: '3.8'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  order-service:
    build:
      context: ./order-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: chandan_bits
      SPRING_DATASOURCE_PASSWORD: password

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  db:
    image: postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: chandan_bits
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
