server:
  port: 8082 # This sets the User Service to run on port 8082

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}        # MongoDB host
      port: ${MONGODB_PORT:27017}            # MongoDB port
      database: ${MONGODB_DATABASE:userdb}   # MongoDB database

management:
  endpoints:
    web:
      exposure:
        include: health, info  # Enables health and info endpoints for monitoring
