server:
  port: 8082 # This sets the User Service to run on port 8082

spring:
  data:
    mongodb:
      host: localhost # MongoDB host (localhost when running locally)
      port: 27017     # MongoDB default port
      database: userdb # Name of the database to use in MongoDB for this service
